#pragma once
#ifndef CATOOL_MAINTOOLBOX_MATHEMATIC_INTERPOLATION_INTERPOLATION_H
#define CATOOL_MAINTOOLBOX_MATHEMATIC_INTERPOLATION_INTERPOLATION_H

#include<cmath>
namespace catool
{
	namespace main_toolbox
	{
		namespace mathematics
		{
		}
	}
}
#endif	//CATOOL_MAINTOOLBOX_MATHEMATIC_INTERPOLATION_INTERPOLATION_H